name: Test

on:
  pull_request:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *" # Every day at 8:00 UTC https://crontab.guru/#0_8_*_*_*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Run prettier linting
        run: npm run lint
      - name: Run unit tests
        run: npm test
      - name: Run build
        run: npm run build:prod
      - name: Upload dist bundle
        uses: actions/upload-artifact@v2
        with:
          name: test-build
          path: dist
      - name: Codecov Upload
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage/lcov.info
